import Ember from 'ember';
var Countries = Ember.A();
Countries.pushObject(Ember.Object.create({display: "Andorra"}));
Countries.pushObject(Ember.Object.create({display: "United Arab Emirates"}));
Countries.pushObject(Ember.Object.create({display: "Afghanistan"}));
Countries.pushObject(Ember.Object.create({display: "Antigua and Barbuda"}));
Countries.pushObject(Ember.Object.create({display: "Anguilla"}));
Countries.pushObject(Ember.Object.create({display: "Albania"}));
Countries.pushObject(Ember.Object.create({display: "Armenia"}));
Countries.pushObject(Ember.Object.create({display: "Netherlands Antilles"}));
Countries.pushObject(Ember.Object.create({display: "Angola"}));
Countries.pushObject(Ember.Object.create({display: "Antarctica"}));
Countries.pushObject(Ember.Object.create({display: "Argentina"}));
Countries.pushObject(Ember.Object.create({display: "American Samoa"}));
Countries.pushObject(Ember.Object.create({display: "Austria"}));
Countries.pushObject(Ember.Object.create({display: "Australia"}));
Countries.pushObject(Ember.Object.create({display: "Aruba"}));
Countries.pushObject(Ember.Object.create({display: "Åland Islands"}));
Countries.pushObject(Ember.Object.create({display: "Azerbaijan"}));
Countries.pushObject(Ember.Object.create({display: "Bosnia and Herzegovina"}));
Countries.pushObject(Ember.Object.create({display: "Barbados"}));
Countries.pushObject(Ember.Object.create({display: "Bangladesh"}));
Countries.pushObject(Ember.Object.create({display: "Belgium"}));
Countries.pushObject(Ember.Object.create({display: "Burkina Faso"}));
Countries.pushObject(Ember.Object.create({display: "Bulgaria"}));
Countries.pushObject(Ember.Object.create({display: "Bahrain"}));
Countries.pushObject(Ember.Object.create({display: "Burundi"}));
Countries.pushObject(Ember.Object.create({display: "Benin"}));
Countries.pushObject(Ember.Object.create({display: "Saint Barthélemy"}));
Countries.pushObject(Ember.Object.create({display: "Bermuda"}));
Countries.pushObject(Ember.Object.create({display: "Brunei Darussalam"}));
Countries.pushObject(Ember.Object.create({display: "Bolivia"}));
Countries.pushObject(Ember.Object.create({display: "Bonaire, Sint Eustatius and Saba"}));
Countries.pushObject(Ember.Object.create({display: "Brazil"}));
Countries.pushObject(Ember.Object.create({display: "Bahamas"}));
Countries.pushObject(Ember.Object.create({display: "Bhutan"}));
Countries.pushObject(Ember.Object.create({display: "Bouvet Island"}));
Countries.pushObject(Ember.Object.create({display: "Botswana"}));
Countries.pushObject(Ember.Object.create({display: "Belarus"}));
Countries.pushObject(Ember.Object.create({display: "Belize"}));
Countries.pushObject(Ember.Object.create({display: "Canada"}));
Countries.pushObject(Ember.Object.create({display: "Cocos (Keeling) Islands"}));
Countries.pushObject(Ember.Object.create({display: "Congo, The Democratic Republic Of The"}));
Countries.pushObject(Ember.Object.create({display: "Central African Republic"}));
Countries.pushObject(Ember.Object.create({display: "Congo"}));
Countries.pushObject(Ember.Object.create({display: "Switzerland"}));
Countries.pushObject(Ember.Object.create({display: "Côte D'Ivoire"}));
Countries.pushObject(Ember.Object.create({display: "Cook Islands"}));
Countries.pushObject(Ember.Object.create({display: "Chile"}));
Countries.pushObject(Ember.Object.create({display: "Cameroon"}));
Countries.pushObject(Ember.Object.create({display: "China"}));
Countries.pushObject(Ember.Object.create({display: "Colombia"}));
Countries.pushObject(Ember.Object.create({display: "Costa Rica"}));
Countries.pushObject(Ember.Object.create({display: "Cuba"}));
Countries.pushObject(Ember.Object.create({display: "Cape Verde"}));
Countries.pushObject(Ember.Object.create({display: "Curaçao"}));
Countries.pushObject(Ember.Object.create({display: "Christmas Island"}));
Countries.pushObject(Ember.Object.create({display: "Cyprus"}));
Countries.pushObject(Ember.Object.create({display: "Czech Republic"}));
Countries.pushObject(Ember.Object.create({display: "Germany"}));
Countries.pushObject(Ember.Object.create({display: "Djibouti"}));
Countries.pushObject(Ember.Object.create({display: "Denmark"}));
Countries.pushObject(Ember.Object.create({display: "Dominica"}));
Countries.pushObject(Ember.Object.create({display: "Dominican Republic"}));
Countries.pushObject(Ember.Object.create({display: "Algeria"}));
Countries.pushObject(Ember.Object.create({display: "Ecuador"}));
Countries.pushObject(Ember.Object.create({display: "Estonia"}));
Countries.pushObject(Ember.Object.create({display: "Egypt"}));
Countries.pushObject(Ember.Object.create({display: "Western Sahara"}));
Countries.pushObject(Ember.Object.create({display: "Eritrea"}));
Countries.pushObject(Ember.Object.create({display: "Spain"}));
Countries.pushObject(Ember.Object.create({display: "Ethiopia"}));
Countries.pushObject(Ember.Object.create({display: "Finland"}));
Countries.pushObject(Ember.Object.create({display: "Fiji"}));
Countries.pushObject(Ember.Object.create({display: "Falkland Islands (Malvinas)"}));
Countries.pushObject(Ember.Object.create({display: "Micronesia, Federated States Of"}));
Countries.pushObject(Ember.Object.create({display: "Faroe Islands"}));
Countries.pushObject(Ember.Object.create({display: "France"}));
Countries.pushObject(Ember.Object.create({display: "Gabon"}));
Countries.pushObject(Ember.Object.create({display: "United Kingdom"}));
Countries.pushObject(Ember.Object.create({display: "Grenada"}));
Countries.pushObject(Ember.Object.create({display: "Georgia"}));
Countries.pushObject(Ember.Object.create({display: "French Guiana"}));
Countries.pushObject(Ember.Object.create({display: "Guernsey"}));
Countries.pushObject(Ember.Object.create({display: "Ghana"}));
Countries.pushObject(Ember.Object.create({display: "Gibraltar"}));
Countries.pushObject(Ember.Object.create({display: "Greenland"}));
Countries.pushObject(Ember.Object.create({display: "Gambia"}));
Countries.pushObject(Ember.Object.create({display: "Guinea"}));
Countries.pushObject(Ember.Object.create({display: "Guadeloupe"}));
Countries.pushObject(Ember.Object.create({display: "Equatorial Guinea"}));
Countries.pushObject(Ember.Object.create({display: "Greece"}));
Countries.pushObject(Ember.Object.create({display: "South Georgia and the South Sandwich Islands"}));
Countries.pushObject(Ember.Object.create({display: "Guatemala"}));
Countries.pushObject(Ember.Object.create({display: "Guam"}));
Countries.pushObject(Ember.Object.create({display: "Guinea-Bissau"}));
Countries.pushObject(Ember.Object.create({display: "Guyana"}));
Countries.pushObject(Ember.Object.create({display: "Hong Kong"}));
Countries.pushObject(Ember.Object.create({display: "Heard and McDonald Islands"}));
Countries.pushObject(Ember.Object.create({display: "Honduras"}));
Countries.pushObject(Ember.Object.create({display: "Croatia"}));
Countries.pushObject(Ember.Object.create({display: "Haiti"}));
Countries.pushObject(Ember.Object.create({display: "Hungary"}));
Countries.pushObject(Ember.Object.create({display: "Indonesia"}));
Countries.pushObject(Ember.Object.create({display: "Ireland"}));
Countries.pushObject(Ember.Object.create({display: "Israel"}));
Countries.pushObject(Ember.Object.create({display: "Isle of Man"}));
Countries.pushObject(Ember.Object.create({display: "India"}));
Countries.pushObject(Ember.Object.create({display: "British Indian Ocean Territory"}));
Countries.pushObject(Ember.Object.create({display: "Iraq"}));
Countries.pushObject(Ember.Object.create({display: "Iran, Islamic Republic Of"}));
Countries.pushObject(Ember.Object.create({display: "Iceland"}));
Countries.pushObject(Ember.Object.create({display: "Italy"}));
Countries.pushObject(Ember.Object.create({display: "Jersey"}));
Countries.pushObject(Ember.Object.create({display: "Jamaica"}));
Countries.pushObject(Ember.Object.create({display: "Jordan"}));
Countries.pushObject(Ember.Object.create({display: "Japan"}));
Countries.pushObject(Ember.Object.create({display: "Kenya"}));
Countries.pushObject(Ember.Object.create({display: "Kyrgyzstan"}));
Countries.pushObject(Ember.Object.create({display: "Cambodia"}));
Countries.pushObject(Ember.Object.create({display: "Kiribati"}));
Countries.pushObject(Ember.Object.create({display: "Comoros"}));
Countries.pushObject(Ember.Object.create({display: "Saint Kitts And Nevis"}));
Countries.pushObject(Ember.Object.create({display: "Korea, Democratic People's Republic Of"}));
Countries.pushObject(Ember.Object.create({display: "Korea, Republic of"}));
Countries.pushObject(Ember.Object.create({display: "Kuwait"}));
Countries.pushObject(Ember.Object.create({display: "Cayman Islands"}));
Countries.pushObject(Ember.Object.create({display: "Kazakhstan"}));
Countries.pushObject(Ember.Object.create({display: "Lao People's Democratic Republic"}));
Countries.pushObject(Ember.Object.create({display: "Lebanon"}));
Countries.pushObject(Ember.Object.create({display: "Saint Lucia"}));
Countries.pushObject(Ember.Object.create({display: "Liechtenstein"}));
Countries.pushObject(Ember.Object.create({display: "Sri Lanka"}));
Countries.pushObject(Ember.Object.create({display: "Liberia"}));
Countries.pushObject(Ember.Object.create({display: "Lesotho"}));
Countries.pushObject(Ember.Object.create({display: "Lithuania"}));
Countries.pushObject(Ember.Object.create({display: "Luxembourg"}));
Countries.pushObject(Ember.Object.create({display: "Latvia"}));
Countries.pushObject(Ember.Object.create({display: "Libya"}));
Countries.pushObject(Ember.Object.create({display: "Morocco"}));
Countries.pushObject(Ember.Object.create({display: "Monaco"}));
Countries.pushObject(Ember.Object.create({display: "Moldova, Republic of"}));
Countries.pushObject(Ember.Object.create({display: "Montenegro"}));
Countries.pushObject(Ember.Object.create({display: "Saint Martin"}));
Countries.pushObject(Ember.Object.create({display: "Madagascar"}));
Countries.pushObject(Ember.Object.create({display: "Marshall Islands"}));
Countries.pushObject(Ember.Object.create({display: "Macedonia, the Former Yugoslav Republic Of"}));
Countries.pushObject(Ember.Object.create({display: "Mali"}));
Countries.pushObject(Ember.Object.create({display: "Myanmar"}));
Countries.pushObject(Ember.Object.create({display: "Mongolia"}));
Countries.pushObject(Ember.Object.create({display: "Macao"}));
Countries.pushObject(Ember.Object.create({display: "Northern Mariana Islands"}));
Countries.pushObject(Ember.Object.create({display: "Martinique"}));
Countries.pushObject(Ember.Object.create({display: "Mauritania"}));
Countries.pushObject(Ember.Object.create({display: "Montserrat"}));
Countries.pushObject(Ember.Object.create({display: "Malta"}));
Countries.pushObject(Ember.Object.create({display: "Mauritius"}));
Countries.pushObject(Ember.Object.create({display: "Maldives"}));
Countries.pushObject(Ember.Object.create({display: "Malawi"}));
Countries.pushObject(Ember.Object.create({display: "Mexico"}));
Countries.pushObject(Ember.Object.create({display: "Malaysia"}));
Countries.pushObject(Ember.Object.create({display: "Mozambique"}));
Countries.pushObject(Ember.Object.create({display: "Namibia"}));
Countries.pushObject(Ember.Object.create({display: "New Caledonia"}));
Countries.pushObject(Ember.Object.create({display: "Niger"}));
Countries.pushObject(Ember.Object.create({display: "Norfolk Island"}));
Countries.pushObject(Ember.Object.create({display: "Nigeria"}));
Countries.pushObject(Ember.Object.create({display: "Nicaragua"}));
Countries.pushObject(Ember.Object.create({display: "Netherlands"}));
Countries.pushObject(Ember.Object.create({display: "Norway"}));
Countries.pushObject(Ember.Object.create({display: "Nepal"}));
Countries.pushObject(Ember.Object.create({display: "Nauru"}));
Countries.pushObject(Ember.Object.create({display: "Niue"}));
Countries.pushObject(Ember.Object.create({display: "New Zealand"}));
Countries.pushObject(Ember.Object.create({display: "Oman"}));
Countries.pushObject(Ember.Object.create({display: "Panama"}));
Countries.pushObject(Ember.Object.create({display: "Peru"}));
Countries.pushObject(Ember.Object.create({display: "French Polynesia"}));
Countries.pushObject(Ember.Object.create({display: "Papua New Guinea"}));
Countries.pushObject(Ember.Object.create({display: "Philippines"}));
Countries.pushObject(Ember.Object.create({display: "Pakistan"}));
Countries.pushObject(Ember.Object.create({display: "Poland"}));
Countries.pushObject(Ember.Object.create({display: "Saint Pierre And Miquelon"}));
Countries.pushObject(Ember.Object.create({display: "Pitcairn"}));
Countries.pushObject(Ember.Object.create({display: "Puerto Rico"}));
Countries.pushObject(Ember.Object.create({display: "Palestinian Territory, Occupied"}));
Countries.pushObject(Ember.Object.create({display: "Portugal"}));
Countries.pushObject(Ember.Object.create({display: "Palau"}));
Countries.pushObject(Ember.Object.create({display: "Paraguay"}));
Countries.pushObject(Ember.Object.create({display: "Qatar"}));
Countries.pushObject(Ember.Object.create({display: "Réunion"}));
Countries.pushObject(Ember.Object.create({display: "Romania"}));
Countries.pushObject(Ember.Object.create({display: "Serbia"}));
Countries.pushObject(Ember.Object.create({display: "Russian Federation"}));
Countries.pushObject(Ember.Object.create({display: "Rwanda"}));
Countries.pushObject(Ember.Object.create({display: "Saudi Arabia"}));
Countries.pushObject(Ember.Object.create({display: "Solomon Islands"}));
Countries.pushObject(Ember.Object.create({display: "Seychelles"}));
Countries.pushObject(Ember.Object.create({display: "Sudan"}));
Countries.pushObject(Ember.Object.create({display: "Sweden"}));
Countries.pushObject(Ember.Object.create({display: "Singapore"}));
Countries.pushObject(Ember.Object.create({display: "Saint Helena"}));
Countries.pushObject(Ember.Object.create({display: "Slovenia"}));
Countries.pushObject(Ember.Object.create({display: "Svalbard And Jan Mayen"}));
Countries.pushObject(Ember.Object.create({display: "Slovakia"}));
Countries.pushObject(Ember.Object.create({display: "Sierra Leone"}));
Countries.pushObject(Ember.Object.create({display: "San Marino"}));
Countries.pushObject(Ember.Object.create({display: "Senegal"}));
Countries.pushObject(Ember.Object.create({display: "Somalia"}));
Countries.pushObject(Ember.Object.create({display: "Suriname"}));
Countries.pushObject(Ember.Object.create({display: "South Sudan"}));
Countries.pushObject(Ember.Object.create({display: "Sao Tome and Principe"}));
Countries.pushObject(Ember.Object.create({display: "El Salvador"}));
Countries.pushObject(Ember.Object.create({display: "Sint Maarten"}));
Countries.pushObject(Ember.Object.create({display: "Syrian Arab Republic"}));
Countries.pushObject(Ember.Object.create({display: "Swaziland"}));
Countries.pushObject(Ember.Object.create({display: "Turks and Caicos Islands"}));
Countries.pushObject(Ember.Object.create({display: "Chad"}));
Countries.pushObject(Ember.Object.create({display: "French Southern Territories"}));
Countries.pushObject(Ember.Object.create({display: "Togo"}));
Countries.pushObject(Ember.Object.create({display: "Thailand"}));
Countries.pushObject(Ember.Object.create({display: "Tajikistan"}));
Countries.pushObject(Ember.Object.create({display: "Tokelau"}));
Countries.pushObject(Ember.Object.create({display: "Timor-Leste"}));
Countries.pushObject(Ember.Object.create({display: "Turkmenistan"}));
Countries.pushObject(Ember.Object.create({display: "Tunisia"}));
Countries.pushObject(Ember.Object.create({display: "Tonga"}));
Countries.pushObject(Ember.Object.create({display: "Turkey"}));
Countries.pushObject(Ember.Object.create({display: "Trinidad and Tobago"}));
Countries.pushObject(Ember.Object.create({display: "Tuvalu"}));
Countries.pushObject(Ember.Object.create({display: "Taiwan, Republic Of China"}));
Countries.pushObject(Ember.Object.create({display: "Tanzania, United Republic of"}));
Countries.pushObject(Ember.Object.create({display: "Ukraine"}));
Countries.pushObject(Ember.Object.create({display: "Uganda"}));
Countries.pushObject(Ember.Object.create({display: "United States Minor Outlying Islands"}));
Countries.pushObject(Ember.Object.create({display: "United States"}));
Countries.pushObject(Ember.Object.create({display: "Uruguay"}));
Countries.pushObject(Ember.Object.create({display: "Uzbekistan"}));
Countries.pushObject(Ember.Object.create({display: "Holy See (Vatican City State)"}));
Countries.pushObject(Ember.Object.create({display: "Saint Vincent And The Grenedines"}));
Countries.pushObject(Ember.Object.create({display: "Venezuela, Bolivarian Republic of"}));
Countries.pushObject(Ember.Object.create({display: "Virgin Islands, British"}));
Countries.pushObject(Ember.Object.create({display: "Virgin Islands, U.S."}));
Countries.pushObject(Ember.Object.create({display: "Vietnam"}));
Countries.pushObject(Ember.Object.create({display: "Vanuatu"}));
Countries.pushObject(Ember.Object.create({display: "Wallis and Futuna"}));
Countries.pushObject(Ember.Object.create({display: "Samoa"}));
Countries.pushObject(Ember.Object.create({display: "Yemen"}));
Countries.pushObject(Ember.Object.create({display: "Mayotte"}));
Countries.pushObject(Ember.Object.create({display: "South Africa"}));
Countries.pushObject(Ember.Object.create({display: "Zambia"}));
Countries.pushObject(Ember.Object.create({display: "Zimbabwe"}));
export default Countries;
